### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by ricardobrg** [tiki/localchain#10]
Test scenario 1:
Create a new block, add to the blockchain, recover and verify it.

Test case 1:
1. Create _n_ blocks with "hello blockchain - _n_" as data. (0 < n < 100)
2. Recover a random block and verify that its contents are correct.

Test case 2:
1. Create _n_ blocks with "hello blockchain - _n_" as data. (0 < n < 100)
2. Recover a random block and verify it against fake content. (verification should fail)

**Comment by mike-audi** [comment]
see localchain_test.dart. most of these if not all are done

**Comment by ricardobrg** [comment]
https://github.com/tiki/localchain/commit/1e7d55b083971b6a2387d384a7f4c986c521c337
